/*
 * gpio.c
 *      Author: Nick
 */


#include "gpio.h"

void init_gpio(void){

	//Enable GPIO clock
	SET_BIT(RCC->IOPENR, RCC_IOPENR_IOPAEN); //Port A clock enable
	SET_BIT(RCC->IOPENR, RCC_IOPENR_IOPBEN); //Port B clock enable
	SET_BIT(RCC->IOPENR, RCC_IOPENR_IOPCEN); //Port C clock enable



	//LED : PB8 (GPO, Push-Pull, Medium Speed,No pull up/down)
	MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODE8, (1 << GPIO_MODER_MODE8_Pos));
	MODIFY_REG(GPIOB->OSPEEDR, GPIO_OSPEEDER_OSPEED8, (1 << GPIO_OSPEEDER_OSPEED8_Pos));

	//IRQ: PB9 (GPI, Push-Pull, Very High Speed, Pull Up)
	MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODE9, (0 << GPIO_MODER_MODE9_Pos));
	MODIFY_REG(GPIOB->OSPEEDR, GPIO_OSPEEDER_OSPEED9, (3 << GPIO_OSPEEDER_OSPEED9_Pos));
	MODIFY_REG(GPIOB->PUPDR, GPIO_PUPDR_PUPD9, (1 << GPIO_PUPDR_PUPD9_Pos));

	//SPI MOSI: PA7 (AF, Push-Pull, Very High Speed, No pull up/down)(AF0:MOSI)
	MODIFY_REG(GPIOA->MODER, GPIO_MODER_MODE7, (2 << GPIO_MODER_MODE7_Pos));
	MODIFY_REG(GPIOA->OSPEEDR, GPIO_OSPEEDER_OSPEED7, (3 << GPIO_OSPEEDER_OSPEED7_Pos));
	MODIFY_REG(GPIOA->AFR[0], GPIO_AFRL_AFSEL7, (0 << GPIO_AFRL_AFSEL7_Pos));

	//SPI MISO: PA6 (AF, Push-Pull, Very High Speed, No pull up/down)(AF0:MISO)
	MODIFY_REG(GPIOA->MODER, GPIO_MODER_MODE6, (2 << GPIO_MODER_MODE6_Pos));
	MODIFY_REG(GPIOA->OSPEEDR, GPIO_OSPEEDER_OSPEED6, (3 << GPIO_OSPEEDER_OSPEED6_Pos));
	MODIFY_REG(GPIOA->AFR[0], GPIO_AFRL_AFSEL6, (0 << GPIO_AFRL_AFSEL6_Pos));

	//SPI SCK: PA5 (AF, Push-Pull, Very High Speed, No pull up/down)(AF0:SCK)
	MODIFY_REG(GPIOA->MODER, GPIO_MODER_MODE5, (2 << GPIO_MODER_MODE5_Pos));
	MODIFY_REG(GPIOA->OSPEEDR, GPIO_OSPEEDER_OSPEED5, (3 << GPIO_OSPEEDER_OSPEED5_Pos));
	MODIFY_REG(GPIOA->AFR[0], GPIO_AFRL_AFSEL5, (0 << GPIO_AFRL_AFSEL5_Pos));


	//I2C SDA: PB7 (AF, Open-Drain, Medium Speed, No pull up/down)(AF1:SDA)
	MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODE7, (2 << GPIO_MODER_MODE7_Pos));
	MODIFY_REG(GPIOB->OSPEEDR, GPIO_OSPEEDER_OSPEED7, (1 << GPIO_OSPEEDER_OSPEED7_Pos));
	MODIFY_REG(GPIOB->AFR[0], GPIO_AFRL_AFSEL7, (1 << GPIO_AFRL_AFSEL7_Pos));
	SET_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT_7);

	//I2C SCL: PB6 (AF, Open-Drain, Medium Speed,No pull up/down)(AF1:SCL)
	MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODE6, (2 << GPIO_MODER_MODE6_Pos));
	MODIFY_REG(GPIOB->OSPEEDR, GPIO_OSPEEDER_OSPEED6, (1 << GPIO_OSPEEDER_OSPEED6_Pos));
	MODIFY_REG(GPIOB->AFR[0], GPIO_AFRL_AFSEL6, (1 << GPIO_AFRL_AFSEL6_Pos));
	SET_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT_6);

	//SPI CSN: PC9 (GPO, Push-Pull, Very High Speed,Pull up)
	MODIFY_REG(GPIOC->MODER, GPIO_MODER_MODE9, (1 << GPIO_MODER_MODE9_Pos));
	MODIFY_REG(GPIOC->OSPEEDR, GPIO_OSPEEDER_OSPEED9, (3 << GPIO_OSPEEDER_OSPEED9_Pos));
	MODIFY_REG(GPIOC->PUPDR, GPIO_PUPDR_PUPD9, (1 << GPIO_PUPDR_PUPD9_Pos));


	//CE : PC7 (GPO, Push-Pull, Very High Speed,No pull up/down)
	MODIFY_REG(GPIOC->MODER, GPIO_MODER_MODE7, (1 << GPIO_MODER_MODE7_Pos));
	MODIFY_REG(GPIOC->OSPEEDR, GPIO_OSPEEDER_OSPEED7, (3 << GPIO_OSPEEDER_OSPEED7_Pos));

	//Button: PC13 (GPI, Push-Pull, Medium Speed, no pull up/down)
	MODIFY_REG(GPIOC->MODER, GPIO_MODER_MODE13, (0 << GPIO_MODER_MODE13_Pos));
	MODIFY_REG(GPIOC->OSPEEDR, GPIO_OSPEEDER_OSPEED13, (1 << GPIO_OSPEEDER_OSPEED13_Pos));


	// R1 Keypad1: PC0 (GPI, Push-Pull, Medium Speed, Pull Down)
	MODIFY_REG(GPIOC->MODER, GPIO_MODER_MODE0, (0 << GPIO_MODER_MODE0_Pos));
	MODIFY_REG(GPIOC->OSPEEDR, GPIO_OSPEEDER_OSPEED0, (1 << GPIO_OSPEEDER_OSPEED0_Pos));
	MODIFY_REG(GPIOC->PUPDR, GPIO_PUPDR_PUPD0, (2 << GPIO_PUPDR_PUPD0_Pos));

	// R2 Keypad2: PC1 (GPI, Push-Pull, Medium Speed, Pull Down)
	MODIFY_REG(GPIOC->MODER, GPIO_MODER_MODE1, (0 << GPIO_MODER_MODE1_Pos));
	MODIFY_REG(GPIOC->OSPEEDR, GPIO_OSPEEDER_OSPEED1, (1 << GPIO_OSPEEDER_OSPEED1_Pos));
	MODIFY_REG(GPIOC->PUPDR, GPIO_PUPDR_PUPD1, (2 << GPIO_PUPDR_PUPD1_Pos));

	// R3 Keypad3: PC2 (GPI, Push-Pull, Medium Speed, Pull Down)
	MODIFY_REG(GPIOC->MODER, GPIO_MODER_MODE2, (0 << GPIO_MODER_MODE2_Pos));
	MODIFY_REG(GPIOC->OSPEEDR, GPIO_OSPEEDER_OSPEED2, (1 << GPIO_OSPEEDER_OSPEED2_Pos));
	MODIFY_REG(GPIOC->PUPDR, GPIO_PUPDR_PUPD2, (2 << GPIO_PUPDR_PUPD2_Pos));

	// R4 Keypad4: PA0  (GPI, Push-Pull, Medium Speed, Pull Down)
	MODIFY_REG(GPIOA->MODER, GPIO_MODER_MODE0, (0 << GPIO_MODER_MODE0_Pos));
	MODIFY_REG(GPIOA->OSPEEDR, GPIO_OSPEEDER_OSPEED0, (1 << GPIO_OSPEEDER_OSPEED0_Pos));
	MODIFY_REG(GPIOA->PUPDR, GPIO_PUPDR_PUPD0, (2 << GPIO_PUPDR_PUPD0_Pos));

	// C1 Keypad7: PB0 (GPO, Push-Pull, Medium Speed, Pull Down)
	MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODE0, (1 << GPIO_MODER_MODE0_Pos));
	MODIFY_REG(GPIOB->OSPEEDR, GPIO_OSPEEDER_OSPEED0, (1 << GPIO_OSPEEDER_OSPEED0_Pos));
	MODIFY_REG(GPIOB->PUPDR, GPIO_PUPDR_PUPD0, (2 << GPIO_PUPDR_PUPD0_Pos));

	// C2 Keypad5: PA1 (GPO, Push-Pull, Medium Speed, Pull Down)
	MODIFY_REG(GPIOA->MODER, GPIO_MODER_MODE1, (1 << GPIO_MODER_MODE1_Pos));
	MODIFY_REG(GPIOA->OSPEEDR, GPIO_OSPEEDER_OSPEED1, (1 << GPIO_OSPEEDER_OSPEED1_Pos));
	MODIFY_REG(GPIOA->PUPDR, GPIO_PUPDR_PUPD1, (2 << GPIO_PUPDR_PUPD1_Pos));

	// C3 Keypad6: PA4 (GPO, Push-Pull, Medium Speed, Pull Down)
	MODIFY_REG(GPIOA->MODER, GPIO_MODER_MODE4, (1 << GPIO_MODER_MODE4_Pos));
	MODIFY_REG(GPIOA->OSPEEDR, GPIO_OSPEEDER_OSPEED4, (1 << GPIO_OSPEEDER_OSPEED4_Pos));
	MODIFY_REG(GPIOA->PUPDR, GPIO_PUPDR_PUPD4, (2 << GPIO_PUPDR_PUPD4_Pos));

	//Microphone: PC3 (GPO, Push-Pull, Medium Speed, Pull Down)
	MODIFY_REG(GPIOC->MODER, GPIO_MODER_MODE3, (1 << GPIO_MODER_MODE3_Pos));
	MODIFY_REG(GPIOC->OSPEEDR, GPIO_OSPEEDER_OSPEED3, (1 << GPIO_OSPEEDER_OSPEED3_Pos));
	MODIFY_REG(GPIOC->PUPDR, GPIO_PUPDR_PUPD3, (2 << GPIO_PUPDR_PUPD3_Pos));



}
